### ISSUE TITLE
hardcoded site.title "Grav" in templates

### ISSUE THREAD

**Issue by terefang** [getgrav/grav-theme-bootstrap#11]
replace: `<a class="navbar-brand" href="{{ base_url == '' ? '/' : base_url }}">Grav</a>`
to: `<a class="navbar-brand" href="{{ base_url == '' ? '/' : base_url }}">{{ site.title|e('html') }}</a>`

in:
modular.html.twig
partials/navigation.html.twig

**Comment by flaviocopes** [comment]
:+1:
