### ISSUE TITLE
js/singlePageNav.min.js missing in Repository

### ISSUE THREAD

**Issue by fmms** [getgrav/grav-theme-bootstrap#12]
Hi,

hightlighting the active section in the menu is currently broken. This is because the file singlePageNav.min.js is missing in the repository and though referenced in 
https://github.com/getgrav/grav-theme-bootstrap/blob/develop/templates/modular.html.twig.

The need file can be found at https://github.com/ChrisWojcik/single-page-nav.

regards

**Comment by flaviocopes** [comment]
Right. `modular.html.twig` was copied from the Antimatter theme, but that JS was not included.
